---
title: "Overview and figure of freshwater phytoplankton traits"
author: "Daniel Gschwentner"
date: "2024-09-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include = F, message = F, warning=F}
# load packages
pck <- c("tidyverse", "cowplot", "ggthemes", "wesandersen", "ggpubr")
lapply(pck, require, character.only = T)
# set plotting theme
theme_set(theme_clean() + 
          theme(text = element_text(color = "black"), 
                axis.text = element_text(color = "black"),
                axis.title = element_text(color = "black"),
                legend.text = element_text(color = "black"),
                legend.title = element_text(color = "black"),
                legend.justification = "center", 
                legend.position = "bottom"))

```

load data

```{r}
# data
fresh.traits <- read_csv("data4input/overview_freshwater_traits.csv")[,-1]

# fix names for consistency
# new trait names
new.traits <- tibble(
  Trait= c("c_per_cell", "K_P_mgL", "K_N_mgL", "Qmin_mg_P_mg_C", "Qmin_mg_N_mg_C",
            "Vmax_mg_P_mg_C", "Vmax_mg_N_mg_C", "umax"),
  Trait.new = c("Cell C", "KP", "KN", "minQP", "minQN", "VmaxP", "VmaxN", "umax")) %>% 
  mutate(
  Trait.new = factor(Trait.new, levels = c("Cell C", "KP", "KN", "minQP", "minQN", "VmaxP", "VmaxN", "umax"))
  )

# new group names
new.groups <- tibble(
  taxon = c("diatom", "green", "cyano"),
  taxon.new = factor(c("diatoms", "greens", "cyanos"), levels = c("diatoms", "greens", "cyanos"))
)

# merge back in
fresh.traits <- merge(fresh.traits, new.traits, by = "Trait")
fresh.traits <- merge(fresh.traits, new.groups, by = "taxon")
```
create plot 

```{r}

(traits.fig <- fresh.traits %>%
  ggplot() + 
  geom_violin(aes(taxon.new, log10(Trait.Value), fill = taxon.new), color = "black") + 
  geom_point(aes(taxon.new, log10(Median.Trait.Value)), color = "black", size = 2) + 
  geom_text(aes(taxon.new, Inf, label = paste("n = ", n)), vjust = 1, col = "black") +
  facet_wrap(Trait.new~., scales = "free_y", nrow = 2, ncol = 4) + 
  scale_fill_viridis_d() + 
  labs(x = NULL, y = expression("log"[10] ~ "Value"), fill = NULL) + 
  theme(legend.position = "none"))

# save figure
save_plot("figures/freshwater_traits_overview.png", traits.fig, base_width = 10, base_height = 4)

```

